import StatisticsLibrary

enum AndroidStatistics {
	private static let mapping: [String: Statistic.Type] = [
		"ACES": Statistics.Aces.self,
		"ACES_SPARED": Statistics.AcesSpared.self,
		"CHOPS": Statistics.ChopOffs.self,
		"CHOPS_SPARED": Statistics.ChopOffsSpared.self,
		"FIVES": Statistics.Fives.self,
		"FIVES_SPARED": Statistics.FivesSpared.self,
		"HEAD_PINS": Statistics.HeadPins.self,
		"HEAD_PINS_SPARED": Statistics.HeadPinsSpared.self,
		"LEFT_CHOPS": Statistics.LeftChopOffs.self,
		"LEFT_CHOPS_SPARED": Statistics.LeftChopOffsSpared.self,
		"LEFT_FIVES": Statistics.LeftFives.self,
		"LEFT_FIVES_SPARED": Statistics.LeftFivesSpared.self,
		"LEFT_SPLITS": Statistics.LeftSplits.self,
		"LEFT_SPLITS_SPARED": Statistics.LeftSplitsSpared.self,
		"LEFT_TAPS": Statistics.LeftTaps.self,
		"LEFT_TAPS_SPARED": Statistics.LeftTapsSpared.self,
		"LEFT_THREES": Statistics.LeftThrees.self,
		"LEFT_THREES_SPARED": Statistics.LeftThreesSpared.self,
		"LEFT_TWELVES": Statistics.LeftTwelves.self,
		"LEFT_TWELVES_SPARED": Statistics.LeftTwelvesSpared.self,
		"RIGHT_CHOPS": Statistics.RightChopOffs.self,
		"RIGHT_CHOPS_SPARED": Statistics.RightChopOffsSpared.self,
		"RIGHT_FIVES": Statistics.RightFives.self,
		"RIGHT_FIVES_SPARED": Statistics.RightFivesSpared.self,
		"RIGHT_SPLITS": Statistics.RightSplits.self,
		"RIGHT_SPLITS_SPARED": Statistics.RightSplitsSpared.self,
		"RIGHT_TAPS": Statistics.RightTaps.self,
		"RIGHT_TAPS_SPARED": Statistics.RightTapsSpared.self,
		"RIGHT_THREES": Statistics.RightThrees.self,
		"RIGHT_THREES_SPARED": Statistics.RightThreesSpared.self,
		"RIGHT_TWELVES": Statistics.RightTwelves.self,
		"RIGHT_TWELVES_SPARED": Statistics.RightTwelvesSpared.self,
		"SPLITS": Statistics.Splits.self,
		"SPLITS_SPARED": Statistics.SplitsSpared.self,
		"TAPS": Statistics.Taps.self,
		"TAPS_SPARED": Statistics.TapsSpared.self,
		"THREES": Statistics.Threes.self,
		"THREES_SPARED": Statistics.ThreesSpared.self,
		"TWELVES": Statistics.Twelves.self,
		"TWELVES_SPARED": Statistics.TwelvesSpared.self,
		"FOULS": Statistics.Fouls.self,
		"SPARE_CONVERSIONS": Statistics.SpareConversions.self,
		"STRIKES": Statistics.Strikes.self,
		"MATCHES_LOST": Statistics.MatchesLost.self,
		"MATCHES_WON": Statistics.MatchesWon.self,
		"MATCHES_TIED": Statistics.MatchesTied.self,
		"MATCHES_PLAYED": Statistics.MatchesPlayed.self,
		"LEFT_OF_MIDDLE_HITS": Statistics.LeftOfMiddleHits.self,
		"RIGHT_OF_MIDDLE_HITS": Statistics.RightOfMiddleHits.self,
		"MIDDLE_HITS": Statistics.MiddleHits.self,
		"STRIKE_MIDDLE_HITS": Statistics.StrikeMiddleHits.self,
		"GAME_AVERAGE": Statistics.GameAverage.self,
		"HIGH_SINGLE_GAME": Statistics.HighSingle.self,
		"NUMBER_OF_GAMES": Statistics.NumberOfGames.self,
		"TOTAL_PIN_FALL": Statistics.TotalPinfall.self,
		"TOTAL_ROLLS": Statistics.TotalRolls.self,
		"AVERAGE_PINS_LEFT_ON_DECK": Statistics.AveragePinsLeftOnDeck.self,
		"TOTAL_PINS_LEFT_ON_DECK": Statistics.TotalPinsLeftOnDeck.self,
		"AVERAGE_FIRST_ROLL": Statistics.FirstRollAverage.self,
		"HIGH_SERIES_OF_3": Statistics.HighSeriesOf3.self,
	]

	static func map(_ statistic: String) -> Statistic.Type? {
		return mapping[statistic]
	}
}
