included:
  - BowlingCompanion/Sources
  - BowlingCompanion/Tests
  - BowlingCompanion/Package.swift

excluded:
  - .build

trailing_comma:
  mandatory_comma: true

disabled_rules:
  - identifier_name
