language: android
jdk:
  - oraclejdk8
android:
  components:

    # Build tools version used by the application
    - tools
    - build-tools-25.0.1

    # SDK tools version used by the application
    - android-25

    # Additional components
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
script:

  # Only building debug because release build in repository does not
  # contain all resources, which cannot be committed due to sensitivity.
  - ./gradlew assembleDebug
