language: android
android:
  components:
    - build-tools-22.0.0
    - android-22
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
before_script:
    - chmod +x BC-Free/gradlew
script:
    - ./BC-Free/gradlew assembleDebug