included:
  - Approach/Sources
  - Approach/Tests
  - Approach/Package.swift

excluded:
  - .build

trailing_comma:
  mandatory_comma: true

type_name:
  excluded:
    - ID

disabled_rules:
  - identifier_name
  - nesting

opt_in_rules:
  - sorted_imports
