name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/android.yml"
      - "android/"

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew ktlintCheck
        env:
          WORKING_DIRECTORY: android
