name: Build iOS

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/build-ios.yml"
      - "ios/Approach/"
      - "ios/ApproachIOS/"
      - "ios/Approach.xcodeproj/"

jobs:
  test:
    runs-on: macOS-12
    defaults:
      run:
        working-directory: ./ios
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 14.2
        run: sudo xcode-select -s /Applications/Xcode_14.2.app
      # - name: Test Features
      #   run: xcodebuild -project Approach.xcodeproj -scheme ApproachFeatureTests -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' test
      - name: Test Units
        run: xcodebuild -project Approach.xcodeproj -scheme ApproachTests -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' test
      - name: Test Snapshots
        run: xcodebuild -project Approach.xcodeproj -scheme ApproachSnapshotTests -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' test
