name: Build

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "BowlingCompanion/"
      - "BowlingCompanionIOS/"
      - "BowlingCompanion.xcodeproj/"

jobs:
  test:
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 14.1
        run: sudo xcode-select -s /Applications/Xcode_14.1.app
      - name: Test
        run: xcodebuild -project BowlingCompanion.xcodeproj -scheme BowlingCompanion -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=16.1' test
